### ISSUE TITLE
封面图暂停播放的角度实现方法可以优化一下

### ISSUE THREAD

**Issue by miantiao-me** [RetroAstro/yinyue#1]
我看你封面图暂停旋转，开始旋转的角度是连续的，看了下源码是使用 JS 计算的。 

其实可以使用 CSS 的 animation-play-state 属性来实现更简单，你可以试试。

**Comment by RetroAstro** [comment]
我最开始想的就是用那个属性来弄的...然后在移动端有bug...至少在IOS上是这样的...所以换了种更兼容的办法。
