### ISSUE TITLE
Keep playing audio in background when going back to home screen

### ISSUE THREAD

**Issue by owen800q** [RetroAstro/yinyue#2]
Hi, I am new to PWA, just curious about when add this PWA to home screen on IOS,  is it possible to keep playing music in background when a user back to home screen

**Comment by RetroAstro** [comment]
> Hi, I am new to PWA, just curious about when add this PWA to home screen on IOS, is it possible to keep playing music in background when a user back to home screen

iOS does not support PWA very well, so it seems like a limitation on iOS.
